# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

# Dependencies required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Optional but recommended, pin the Python dependencies to the same
# versions used in production.
submodules:
  include: all